[workspace]
members = ["crates/connection-string-parser"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.0.32", features = ["derive"] }

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
