name: Setup Dasel

description: Setup dasel cli

inputs:
  version:
    description: The version of dasel to install
    required: true
    default: "2.0.2"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p "$PWD/tools"
        curl -sSLf "https://github.com/TomWright/dasel/releases/download/v${{ inputs.version }}/dasel_linux_amd64" -L -o ./tools/dasel
        chmod +x ./tools/dasel

    - shell: bash
      run: echo "$PWD/tools" >> $GITHUB_PATH

    - shell: bash
      run: dasel --version
