# This action is responsible for releasing only the library crates to crates.io.
name: Release libraries

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: Which project to publish
        options:
          - avatars
          - arch-mirror

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  publish:
    if: github.repository_owner == 'IgnisDa'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo publish --package "${{ github.event.inputs.project }}" --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
